"use client";

import { FormEvent, useState } from "react";

const pairs = ["🐶", "🌼", "🍎", "🐶", "🌼", "🍎"];
export default function GamesPanel({ sessionKey }: { sessionKey: () => string }) {
  const [game, setGame] = useState<"word-memory" | "memory-match" | "walk-challenge" | null>(null);
  const [words, setWords] = useState<string[]>([]); const [hidden, setHidden] = useState(false); const [recall, setRecall] = useState(""); const [result, setResult] = useState("");
  const [open, setOpen] = useState<number[]>([]); const [matched, setMatched] = useState<number[]>([]); const [steps, setSteps] = useState("");
  async function log(gameType: string, data: Record<string, unknown>) { const response = await fetch("/api/games", { method: "POST", headers: { "Content-Type": "application/json", "x-session-key": sessionKey() }, body: JSON.stringify({ gameType, ...data }) }); if (!response.ok) throw new Error("Progress could not be saved."); return response.json(); }
  async function start(type: typeof game) { if (!type) return; setGame(type); setResult(""); setOpen([]); setMatched([]); if (type === "word-memory") { const data = await log(type, { action: "start" }); setWords(data.words); setHidden(false); } else await log(type, { action: "start" }); }
  function flip(index: number) { if (matched.includes(index) || open.includes(index) || open.length === 2) return; const next = [...open, index]; setOpen(next); if (next.length === 2) { if (pairs[next[0]] === pairs[next[1]]) { const done = [...matched, ...next]; setMatched(done); setOpen([]); if (done.length === pairs.length) { setResult("Wonderful—you matched every pair!"); void log("memory-match", { score: 3 }); } } else setTimeout(() => setOpen([]), 700); } }
  async function scoreWords(event: FormEvent) { event.preventDefault(); const answers = recall.toLowerCase().split(/[ ,]+/).filter(Boolean); const score = words.filter((word) => answers.includes(word.toLowerCase())).length; setResult(score ? `You remembered ${score} of 5. Well done!` : "Good try! Every practice helps your memory."); await log("word-memory", { score }); }
  async function saveSteps(event: FormEvent) { event.preventDefault(); const count = Number(steps); if (!Number.isInteger(count) || count < 0) return; setResult(count ? `Lovely work—${count.toLocaleString()} steps logged!` : "A gentle start still counts. Try a few steps when you’re ready."); await log("walk-challenge", { steps: count }); }

  return <div className="mx-auto max-w-5xl p-4"><section className="rounded-3xl border-2 border-blue-100 bg-white p-5 shadow-sm"><h2 className="text-3xl font-black">Games with Bluey</h2><p className="mt-1">Choose something light and fun. Take all the time you need.</p><div className="mt-5 grid gap-3 md:grid-cols-3"><button onClick={() => void start("word-memory")} className="focus-ring min-h-28 rounded-2xl bg-amber-100 p-4 text-xl font-black">📝 Word Memory</button><button onClick={() => void start("memory-match")} className="focus-ring min-h-28 rounded-2xl bg-blue-100 p-4 text-xl font-black">🃏 Memory Match</button><button onClick={() => void start("walk-challenge")} className="focus-ring min-h-28 rounded-2xl bg-emerald-100 p-4 text-xl font-black">🚶 Walk Challenge</button></div></section>
    {game === "word-memory" && <section className="mt-4 rounded-3xl border-2 border-blue-100 bg-white p-6 text-center"><h3 className="text-2xl font-black">Remember these five words</h3>{!hidden ? <><div className="my-6 flex flex-wrap justify-center gap-3">{words.map((word) => <span key={word} className="rounded-xl bg-amber-100 px-4 py-3 text-xl font-bold">{word}</span>)}</div><button className="focus-ring min-h-14 rounded-2xl bg-[#175cd3] px-6 font-bold text-white" onClick={() => setHidden(true)}>I’m ready to recall</button></> : <form onSubmit={scoreWords}><label className="mt-4 block font-bold">Type the words you remember<input value={recall} onChange={(event) => setRecall(event.target.value)} className="focus-ring mx-auto mt-2 min-h-14 w-full max-w-lg rounded-xl border-2 border-slate-300 px-4"/></label><button className="focus-ring mt-4 min-h-14 rounded-2xl bg-[#175cd3] px-6 font-bold text-white">Check my memory</button></form>}</section>}
    {game === "memory-match" && <section className="mt-4 rounded-3xl border-2 border-blue-100 bg-white p-6 text-center"><h3 className="text-2xl font-black">Find the three matching pairs</h3><div className="mx-auto mt-5 grid max-w-md grid-cols-3 gap-3">{pairs.map((symbol, index) => <button key={index} aria-label={`Card ${index + 1}`} onClick={() => flip(index)} className="focus-ring aspect-square rounded-2xl bg-blue-700 text-4xl text-white">{open.includes(index) || matched.includes(index) ? symbol : "?"}</button>)}</div></section>}
    {game === "walk-challenge" && <form onSubmit={saveSteps} className="mt-4 rounded-3xl border-2 border-blue-100 bg-white p-6 text-center"><h3 className="text-2xl font-black">Log today’s steps</h3><label className="mt-4 block font-bold">How many steps did you take?<input type="number" min="0" required value={steps} onChange={(event) => setSteps(event.target.value)} className="focus-ring mx-auto mt-2 min-h-14 w-full max-w-sm rounded-xl border-2 border-slate-300 px-4"/></label><button className="focus-ring mt-4 min-h-14 rounded-2xl bg-[#175cd3] px-6 font-bold text-white">Save my steps</button></form>}
    {result && <p className="mt-4 rounded-2xl bg-emerald-50 p-5 text-center text-xl font-bold" role="status">{result}</p>}
  </div>;
}
