"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

type Reminder = { id: string; type: string; label: string; schedule_time: string | null; repeat_interval_minutes: number | null; is_active: boolean; session_key?: string | null };
const empty = { id: "", type: "medication", label: "", schedule_time: "09:00", repeat_interval_minutes: "", is_active: true };

export default function RemindersPanel({ sessionKey }: { sessionKey: () => string }) {
  const [items, setItems] = useState<Reminder[]>([]); const [form, setForm] = useState(empty);
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/reminders", { headers: { "x-session-key": sessionKey() } }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setItems(data.reminders); }, [sessionKey]);
  useEffect(() => { load().catch((caught) => setError(caught instanceof Error ? caught.message : "Reminders could not load.")); }, [load]);

  async function save(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError("");
    try { const response = await fetch("/api/reminders", { method: form.id ? "PATCH" : "POST", headers: { "Content-Type": "application/json", "x-session-key": sessionKey() }, body: JSON.stringify({ ...form, repeat_interval_minutes: form.repeat_interval_minutes || null }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setForm(empty); await load(); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "Reminder could not be saved."); }
    finally { setBusy(false); }
  }
  async function remove(id: string) { if (!confirm("Delete this reminder?")) return; const response = await fetch(`/api/reminders?id=${encodeURIComponent(id)}`, { method: "DELETE", headers: { "x-session-key": sessionKey() } }); const data = await response.json(); if (!response.ok) { setError(data.error); return; } await load(); }
  function edit(item: Reminder) { if (!item.session_key) { setError("Demo reminders are examples. Add your own reminder to edit it."); return; } setForm({ id: item.id, type: item.type, label: item.label, schedule_time: item.schedule_time?.slice(0, 5) ?? "", repeat_interval_minutes: item.repeat_interval_minutes ? String(item.repeat_interval_minutes) : "", is_active: item.is_active }); }

  return <div className="mx-auto grid max-w-6xl gap-4 p-4 md:grid-cols-[1fr_1fr]">
    <section className="rounded-3xl border-2 border-blue-100 bg-white p-5 shadow-sm"><h2 className="text-3xl font-black">Your reminders</h2><p className="mt-1 text-slate-600">Medication, water, toilet breaks, and gentle strolls.</p><div className="mt-5 space-y-3">{items.map((item) => <article key={item.id} className="rounded-2xl border-2 border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><span className="text-sm font-bold uppercase text-blue-700">{item.type}</span><h3 className="text-xl font-bold">{item.label}</h3><p>{item.schedule_time ? `Every day at ${item.schedule_time.slice(0, 5)}` : `Every ${item.repeat_interval_minutes} minutes`}</p></div><span aria-label={item.is_active ? "Active" : "Paused"}>{item.is_active ? "🟢" : "⏸️"}</span></div><div className="mt-3 flex gap-2"><button className="focus-ring min-h-12 rounded-xl border-2 border-blue-300 px-4 font-bold" onClick={() => edit(item)}>Edit</button>{item.session_key && <button className="focus-ring min-h-12 rounded-xl border-2 border-red-200 px-4 font-bold text-red-700" onClick={() => void remove(item.id)}>Delete</button>}</div></article>)}{!items.length && <p className="rounded-2xl bg-blue-50 p-5">Add your first reminder.</p>}</div></section>
    <form onSubmit={save} className="h-fit rounded-3xl border-2 border-blue-100 bg-white p-5 shadow-sm"><h2 className="text-2xl font-black">{form.id ? "Edit reminder" : "Add a reminder"}</h2><label className="mt-4 block font-bold">Type<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })} className="focus-ring mt-1 min-h-14 w-full rounded-xl border-2 border-slate-300 px-3"><option value="medication">Medication</option><option value="water">Water</option><option value="toilet">Toilet break</option><option value="stroll">Stroll</option><option value="custom">Something else</option></select></label><label className="mt-4 block font-bold">What should Bluey say?<input required maxLength={120} value={form.label} onChange={(event) => setForm({ ...form, label: event.target.value })} className="focus-ring mt-1 min-h-14 w-full rounded-xl border-2 border-slate-300 px-3" placeholder="Take my blood pressure pill"/></label><label className="mt-4 block font-bold">Daily time<input type="time" value={form.schedule_time} onChange={(event) => setForm({ ...form, schedule_time: event.target.value, repeat_interval_minutes: "" })} className="focus-ring mt-1 min-h-14 w-full rounded-xl border-2 border-slate-300 px-3"/></label><label className="mt-4 block font-bold">Or repeat every (minutes)<input type="number" min="15" max="1440" value={form.repeat_interval_minutes} onChange={(event) => setForm({ ...form, repeat_interval_minutes: event.target.value, schedule_time: "" })} className="focus-ring mt-1 min-h-14 w-full rounded-xl border-2 border-slate-300 px-3" placeholder="60"/></label><label className="mt-4 flex min-h-12 items-center gap-3 font-bold"><input type="checkbox" checked={form.is_active} onChange={(event) => setForm({ ...form, is_active: event.target.checked })} className="size-6"/>Reminder is active</label>{error && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 font-bold text-red-800">{error}</p>}<button disabled={busy} className="focus-ring mt-5 min-h-14 w-full rounded-2xl bg-[#175cd3] font-bold text-white disabled:opacity-50">{busy ? "Saving…" : form.id ? "Save changes" : "Add reminder"}</button>{form.id && <button type="button" onClick={() => setForm(empty)} className="focus-ring mt-2 min-h-12 w-full rounded-xl border-2 border-slate-300">Cancel edit</button>}</form>
  </div>;
}
